[[services]]
name = "msa-msb"
source = "msa-msb/Dockerfile"
env = "PORT=8081,8082"

[[services]]
name = "auth"
source = "authserver/Dockerfile"
env = "PORT=8083"

[[services]]
name = "gateway"
source = "api-gateway/Dockerfile"
env = "PORT=8080"

[[services]]
name = "eureka"
source = "idgs15/Dockerfile"
env = "PORT=8761"
