[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
loglevel=info
childlogdir=/tmp

[program:eureka]
command=java -jar /app/idgs15.jar
stdout_logfile=/tmp/eureka.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/eureka.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=10

[program:auth]
command=java -jar /app/authserver.jar
stdout_logfile=/tmp/auth.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/auth.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=20

[program:ms-a]
command=java -jar /app/ms-a.jar
stdout_logfile=/tmp/ms-a.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/ms-a.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=30

[program:ms-b]
command=java -jar /app/ms-b.jar
stdout_logfile=/tmp/ms-b.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/ms-b.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=30

[program:gateway]
command=java -jar /app/api-gateway.jar
stdout_logfile=/tmp/gateway.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/gateway.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=40