[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
loglevel=info
childlogdir=/tmp

[program:ms-a]
command=java -jar /workspace/ms-a/target/*.jar
stdout_logfile=/tmp/ms-a.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/ms-a.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=30

[program:ms-b]
command=java -jar /workspace/ms_b/target/*.jar
stdout_logfile=/tmp/ms-b.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/ms-b.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
autorestart=true
startsecs=30
startretries=5
priority=30
