spring.application.name=ms-a
server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.railway.internal:5432/dwint_msa}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:HuTzSEZybsxGpADPTGYQIKasWXxDRwAI}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:true}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
