-- ============================================================
-- Setup de PostgreSQL para ms-a (dwint_msa)
-- ============================================================
\connect dwint_msa

CREATE TABLE IF NOT EXISTS entity_a (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombrea VARCHAR(255)
);
