-- ============================================================
-- Setup de PostgreSQL para ms_b (dwint_msb)
-- ============================================================
\connect dwint_msb

CREATE TABLE IF NOT EXISTS entity_b (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreb VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS entity_b_entity_a (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entitya_id INT,
    entityb_id INT REFERENCES entity_b(id) ON DELETE CASCADE
);
